# Generated by Django 2.0.2 on 2020-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='hunter',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='complain',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complain',
            name='ministry',
            field=models.CharField(max_length=100),
        ),
    ]
