# Generated by Django 3.0.7 on 2020-07-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_auto_20200524_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complain',
            name='dateApprove',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
